notifications:
  email: false
  slack:
    rooms:
      secure: 1cCV9MCdY+Vb7WPhMqrOPypqPP3hFfXEbutyYE9SMBi9jVycUVRL7GDRTrUR3V2W2hQ491fjIYST4XqEF+DhDZ+IHLmX/qqklVoj+uVViG2Q/XIxqUGLXYBcKHWrxoZi2ebMWjFnh7+0PBh6tEXhQ3JSBcrCNgD/y5JvmlqUugLTFY//MdM0rocegni2d0iTxJajH8fyfn7GmhxfHc2CSjP9R9iXFgOsg862hDHnSdHWwctt/R/Z1LsCLvruJ17z7nOuLPAtkHn3/QjQM691hV3kuiWtSKWL1HmNf2eE7fBtF/1/XOY6pxpmn/OirKarFXI5e7cnT1NBxdbe/sKEa3dVWrYBCEB2Ys1cK0vzqfd182SZdL59kLmesYTWXXO0vSa0IxxU6dbPbc7QSjhXFb3oFQ7Dt7npR/jqhfuaF6ZIyJfl6rHXc+Tm6t3Gtxv901wOswj7Vr8XOy+d+Mx7XfLZ2psndxaUcj7mmo2Fx9dGaF9f32tS8ozRUteTeUWs/kuCCrpOCDcn75qwSwiaLaNk8KhMdHytJrLnlzlXeM67VKJHCc424krkzNRj96ixtA38mqGX4A8Jlt3uigZg3xnHr+1bgNLvwl+XlGxPYpiqty+XBpj2n0G8jyXfd3I9+yVS34j/5XZNJHaV4lN2VkFWR5BXopCLtIEypcecv7Y=
    on_success: always
    on_failure: always

stages:
- name: BUILD
  if: commit_message !~ /\[skip build\]/
- name: TEST
  if: commit_message !~ /\[skip test\]/

jobs:
  include:

  - stage: BUILD
    language: node_js
    node_js:
    - '16'
    services:
    - docker
    script:
    - bash .travis.build.sh

  - stage: TEST
    language: node_js
    node_js:
    - '16'
    services:
    - mongodb
    - docker
    env:
    - CC_TEST_REPORTER_ID=3f30a58b36c68a3e9436795b8a99f2f134a6d884ceb7e055ee7b39589886281d
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    - "$JAVA_HOME/bin/java -version"
    - git clone https://github.com/kalisio/krawler.git && cd krawler && yarn install && yarn link && cd ..
    - yarn link @kalisio/krawler
    - yarn global add @weacast/gtiff2json@2.0.2
    - yarn global add @weacast/grib2json@2.0.2
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
