ARG TAG=latest
FROM  weacast/weacast-gfs:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 20 * * * *"

COPY jobfile-gfs-world.js .

CMD krawler --cron "$CRON" --success-rate 0.75 jobfile-gfs-world.js
