ARG TAG=latest
FROM  weacast/weacast-gfs:${TAG}

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG SYNC_DB_URL=mongodb://mongodb:27017/weacast
ENV SYNC_DB_URL=$SYNC_DB_URL

COPY jobfile-gfs-isobaric-world.js .

CMD node ./krawler --cron "0 25,55 * * * *" --sync "$SYNC_DB_URL" jobfile-gfs-isobaric-world.js
