FROM  weacast/weacast-arpege

MAINTAINER Kalisio <contact@kalisio.xyz>

COPY jobfile-arpege-europe.js .

# For dev testing
CMD node ./krawler --cron "30 */15 * * * *" --sync "mongodb://mongodb:27017/weacast" jobfile-arpege-europe.js
# CMD krawler --cron "30 */15 * * * *" --sync "mongodb://mongodb:27017/weacast" jobfile-arpege-europe.js
