ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ARG SYNC_DB_URL=mongodb://mongodb:27017/weacast
ENV SYNC_DB_URL=$SYNC_DB_URL

COPY jobfile-arpege-isobaric-europe.js .

CMD node /opt/krawler --cron "0 10,40 * * * *" --sync "$SYNC_DB_URL" jobfile-arpege-isobaric-europe.js
