ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ARG SYNC_DB_URL=mongodb://mongodb:27017/weacast
ENV SYNC_DB_URL=$SYNC_DB_URL

COPY job-arome.js .
COPY jobfile-arome-france.js .

CMD node /opt/krawler --cron "0 20,50 * * * *" --sync "$SYNC_DB_URL" jobfile-arome-france.js
