ARG TAG=latest
FROM  weacast/weacast-arome:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 0 * * * *"

COPY jobfile-arome-france.js .

CMD node /opt/krawler --cron "$CRON" jobfile-arome-france.js
