FROM  weacast/weacast-arpege

MAINTAINER Kalisio <contact@kalisio.xyz>

COPY job-arome.js .
COPY jobfile-arome-france.js .

CMD node ./krawler --cron "0 20,50 * * * *" --sync "mongodb://mongodb:27017/weacast" jobfile-arome-france.js
