ARG TAG=latest
FROM  weacast/weacast-gfs:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ARG SYNC_DB_URL=mongodb://mongodb:27017/weacast
ENV SYNC_DB_URL=$SYNC_DB_URL

COPY jobfile-gfs-world.js .

CMD node /opt/krawler --cron "0 0,30 * * * *" --sync "$SYNC_DB_URL" jobfile-gfs-world.js
