ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

COPY jobfile-arpege-europe.js .

CMD node /opt/krawler --cron "0 15,45 * * * *" jobfile-arpege-europe.js
