ARG TAG=latest
FROM  weacast/weacast-gfs:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

COPY jobfile-gfs-isobaric-world.js .

CMD node /opt/krawler --cron "0 25,55 * * * *" jobfile-gfs-isobaric-world.js
