ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 40 * * * *"

COPY jobfile-arpege-isobaric-world.js .

CMD krawler --cron "$CRON" --success-rate 0.75 jobfile-arpege-isobaric-world.js
