ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 45 * * * *"

COPY --chown=node:node jobfile-arpege-isobaric-europe.js .

CMD krawler --cron "$CRON" jobfile-arpege-isobaric-europe.js
