ARG TAG=latest
FROM  weacast/weacast-arome:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

COPY jobfile-arome-france-high.js .

CMD node /opt/krawler --cron "0 05,35 * * * *" jobfile-arome-france-high.js
