ARG TAG=latest
FROM  weacast/weacast-arome:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 5 * * * *"

COPY --chown=node:node jobfile-arome-france-high.js .

CMD krawler --cron "$CRON" jobfile-arome-france-high.js
