ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 40 * * * *"

COPY --chown=node:node jobfile-arpege-isobaric-world.js .

CMD krawler --cron "$CRON" jobfile-arpege-isobaric-world.js
