ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG SYNC_DB_URL=mongodb://mongodb:27017/weacast
ENV SYNC_DB_URL=$SYNC_DB_URL

COPY job-arome.js .
COPY jobfile-arome-france-high.js .

CMD node ./krawler --cron "0 05,35 * * * *" --sync "$SYNC_DB_URL" jobfile-arome-france-high.js
