ARG TAG=latest
FROM  weacast/weacast-arpege:${TAG}

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ENV CRON="0 10 * * * *"

COPY jobfile-arpege-world.js .

CMD node /opt/krawler --cron "$CRON" jobfile-arpege-world.js
