FROM  weacast/weacast-gfs

MAINTAINER Kalisio <contact@kalisio.xyz>

COPY jobfile-gfs-world.js .

CMD node ./krawler --cron "0 0,30 * * * *" --sync "mongodb://mongodb:27017/weacast" jobfile-gfs-world.js
